on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Render Rmarkdown

jobs:
  render:
    name: Render Rmarkdown files
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::dplyr
            any::tidyr
            any::readr
            any::rmarkdown
            any::knitr
            any::kableExtra
            any::lubridate
            any::ggplot2
            any::cowplot
            any::ggmap
            any::agricolae
            any::broom

      - name: Render Rmarkdown files
        run: |
          Rscript --verbose ./render.R
