on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Render Rmarkdown

jobs:
  render:
    name: Render Rmarkdown files
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown and remotes packages
        run: |
          install.packages(c("remotes", "dplyr", "tidyr", "readr", "rmarkdown", "knitr", "kableExtra", "lubridate", "ggplot2", "cowplot", "ggmap", "agricolae", "broom"))
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          Rscript -e --verbose rmarkdown::render("SLA.Rmd")
